<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241119130905 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE avion (immatriculation VARCHAR(6) NOT NULL, avion_companie_id INT DEFAULT NULL, avion_statue_id INT NOT NULL, PRIMARY KEY(immatriculation))');
        $this->addSql('CREATE INDEX IDX_234D9D3813E7B23E ON avion (avion_companie_id)');
        $this->addSql('CREATE INDEX IDX_234D9D385F2A3A7B ON avion (avion_statue_id)');
        $this->addSql('CREATE TABLE companies (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, companie_nom VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE intervention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, intervention_commentaire VARCHAR(1024) DEFAULT NULL, intervention_date_creation TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, intervention_date_debut TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, intervention_date_fin TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, avion_immatriculation VARCHAR(6) NOT NULL, intervention_type_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D11814AB4FBFC207 ON intervention (avion_immatriculation)');
        $this->addSql('CREATE INDEX IDX_D11814AB8EA2F8F6 ON intervention (intervention_type_id)');
        $this->addSql('CREATE TABLE statues (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statue_nom VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_intervention (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_intervention_nom VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE avion ADD CONSTRAINT FK_234D9D3813E7B23E FOREIGN KEY (avion_companie_id) REFERENCES companies (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE avion ADD CONSTRAINT FK_234D9D385F2A3A7B FOREIGN KEY (avion_statue_id) REFERENCES statues (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE intervention ADD CONSTRAINT FK_D11814AB4FBFC207 FOREIGN KEY (avion_immatriculation) REFERENCES avion (immatriculation) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE intervention ADD CONSTRAINT FK_D11814AB8EA2F8F6 FOREIGN KEY (intervention_type_id) REFERENCES type_intervention (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE avion DROP CONSTRAINT FK_234D9D3813E7B23E');
        $this->addSql('ALTER TABLE avion DROP CONSTRAINT FK_234D9D385F2A3A7B');
        $this->addSql('ALTER TABLE intervention DROP CONSTRAINT FK_D11814AB4FBFC207');
        $this->addSql('ALTER TABLE intervention DROP CONSTRAINT FK_D11814AB8EA2F8F6');
        $this->addSql('DROP TABLE avion');
        $this->addSql('DROP TABLE companies');
        $this->addSql('DROP TABLE intervention');
        $this->addSql('DROP TABLE statues');
        $this->addSql('DROP TABLE type_intervention');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
