<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Avion extends \App\Entity\Avion implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'AvionCompanie' => [parent::class, 'AvionCompanie', null],
        "\0".parent::class."\0".'AvionStatue' => [parent::class, 'AvionStatue', null],
        "\0".parent::class."\0".'immatriculation' => [parent::class, 'immatriculation', null],
        'AvionCompanie' => [parent::class, 'AvionCompanie', null],
        'AvionStatue' => [parent::class, 'AvionStatue', null],
        'immatriculation' => [parent::class, 'immatriculation', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
