<?php

namespace ContainerXnNJv13;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MnwatdMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mnwatdM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mnwatdM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avionRepository' => ['privates', 'App\\Repository\\AvionRepository', 'getAvionRepositoryService', true],
        ], [
            'avionRepository' => 'App\\Repository\\AvionRepository',
        ]);
    }
}
