<?php

namespace ContainerXnNJv13;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7EdJbxrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7EdJbxr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7EdJbxr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
            'statuesRepository' => ['privates', 'App\\Repository\\StatuesRepository', 'getStatuesRepositoryService', true],
        ], [
            'serializer' => '?',
            'statuesRepository' => 'App\\Repository\\StatuesRepository',
        ]);
    }
}
