<?php

namespace ContainerXnNJv13;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MobVkwiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MobVkwi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MobVkwi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'statue' => ['privates', '.errored..service_locator.MobVkwi.App\\Entity\\Statues', NULL, 'Cannot autowire service ".service_locator.MobVkwi": it needs an instance of "App\\Entity\\Statues" but this type has been excluded in "config/services.yaml".'],
        ], [
            'statue' => 'App\\Entity\\Statues',
        ]);
    }
}
