<?php

namespace ContainerXnNJv13;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yya1xgCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yya1xgC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yya1xgC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avion' => ['privates', '.errored..service_locator.yya1xgC.App\\Entity\\Avion', NULL, 'Cannot autowire service ".service_locator.yya1xgC": it needs an instance of "App\\Entity\\Avion" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'avion' => 'App\\Entity\\Avion',
            'entityManager' => '?',
        ]);
    }
}
