<?php

namespace ContainerXnNJv13;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatuesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\StatuesType' shared autowired service.
     *
     * @return \App\Form\StatuesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/StatuesType.php';

        return $container->privates['App\\Form\\StatuesType'] = new \App\Form\StatuesType();
    }
}
