<?php

namespace ContainerP2sLKLe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TcuxbjpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Tcuxbjp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Tcuxbjp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avion' => ['privates', '.errored..service_locator.Tcuxbjp.App\\Entity\\Avion', NULL, 'Cannot autowire service ".service_locator.Tcuxbjp": it needs an instance of "App\\Entity\\Avion" but this type has been excluded in "config/services.yaml".'],
        ], [
            'avion' => 'App\\Entity\\Avion',
        ]);
    }
}
