<?php

namespace ContainerP2sLKLe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UF8YHojService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.UF8YHoj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UF8YHoj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'companies' => ['privates', '.errored..service_locator.UF8YHoj.App\\Entity\\Companies', NULL, 'Cannot autowire service ".service_locator.UF8YHoj": it needs an instance of "App\\Entity\\Companies" but this type has been excluded in "config/services.yaml".'],
            'companiesRepository' => ['privates', 'App\\Repository\\CompaniesRepository', 'getCompaniesRepositoryService', true],
            'entityManagerInterface' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'companies' => 'App\\Entity\\Companies',
            'companiesRepository' => 'App\\Repository\\CompaniesRepository',
            'entityManagerInterface' => '?',
        ]);
    }
}
