<?php

namespace ContainerP2sLKLe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8A835JfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8A835Jf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8A835Jf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'avionRepository' => ['privates', 'App\\Repository\\AvionRepository', 'getAvionRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'avionRepository' => 'App\\Repository\\AvionRepository',
            'paginator' => '?',
        ]);
    }
}
