<?php

namespace ContainerP2sLKLe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompaniesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UF8YHoj.App\Entity\Companies' shared service.
     *
     * @return \App\Entity\Companies
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.UF8YHoj": it needs an instance of "App\\Entity\\Companies" but this type has been excluded in "config/services.yaml".');
    }
}
