<?php

namespace ContainerP2sLKLe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatues2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.r.eSliI.App\Entity\Statues' shared service.
     *
     * @return \App\Entity\Statues
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.r.eSliI": it needs an instance of "App\\Entity\\Statues" but this type has been excluded in "config/services.yaml".');
    }
}
