<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP2sLKLe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP2sLKLe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP2sLKLe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP2sLKLe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP2sLKLe\App_KernelDevDebugContainer([
    'container.build_hash' => 'P2sLKLe',
    'container.build_id' => '562cc0f8',
    'container.build_time' => 1732803560,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP2sLKLe');
