<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW44qPaR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW44qPaR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW44qPaR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW44qPaR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW44qPaR\App_KernelDevDebugContainer([
    'container.build_hash' => 'W44qPaR',
    'container.build_id' => 'a3d1edba',
    'container.build_time' => 1732806568,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW44qPaR');
